name: TypeScript Node.js Unit testing

on:
  push:
    branches:
      - main
      - 'releases/**'

env:
  NODE_VERSION: 20.x

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ env.NODE_VERSION }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test